name: crime_finder
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  geolocator: ^11.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  latlong2: ^0.9.1
  provider: ^6.1.2
  url_launcher: ^6.2.6
  flutter_map_location_marker: any
  flutter_secure_storage: ^5.0.2
  hive_generator: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/
